// @ts-check

import eslint from "@eslint/js";
import globals from "globals";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";
import { createTypeScriptImportResolver } from "eslint-import-resolver-typescript";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";

export default defineConfig([
    {
        basePath: "resources/js",
        files: ["**/*.{js,ts}"],
        ignores: [
            // The followng files are auto-generated by laravel/wayfinder
            // and we don't have to lint them
            "routes/**",
            "actions/**",
        ],
        rules: {
            // Usually when you work with typescript for browser scripting -
            // you'll find yourself using "any" keyword, so if you
            // found disallowing it a bottleneck to you
            // use "warn" or "off" instead of "error"
            "@typescript-eslint/no-explicit-any": "error",
        },
        languageOptions: {
            parserOptions: {
                tsconfigRootDir: "/",
            },
            globals: globals.browser,
        },
        settings: {
            "import/resolver": [
                createTypeScriptImportResolver({
                    project: "tsconfig.json",
                }),
            ],
        },
        extends: [
            eslint.configs.recommended,
            tseslint.configs.recommended,
            eslintPluginPrettierRecommended,
        ],
    },
]);
